### ISSUE TITLE
Errors related to the Gmac structure and some imports

### ISSUE THREAD

**Issue by Devika153** [jtbr/FreeRTOS-TCP_SAMV71_NetIntf#3]
Thanks for sharing your work! I'm currently trying to use your project in MPLAB X IDE and getting some errors related to the Gmac structure and some includes as seen in the image. Do you have any idea about them? Thanks!

![NetIntfErrors](https://user-images.githubusercontent.com/33452383/127628746-0e83183d-35c8-4076-8734-67e51f8e4b84.PNG)

**Comment by jtbr** [comment]
This apparently points to some difference in hardware from what this was developed on, as the `Gmac` struct is pointing to hardware registers.
